# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Moya_Ex' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Moya_Ex
  pod 'Moya'
  
  target 'Moya_ExTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'Moya_ExUITests' do
    # Pods for testing
  end

end
